name: landmark_navigation_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_google_places_sdk: any
  http: ^1.2.0
  google_polyline_algorithm: ^3.1.0
  flutter_riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/assets/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "android/app/src/main/res/assets/ic_launcher.png"

flutter:
  assets:
    - .env
  uses-material-design: true

