// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbWrFMbZgxfSnbxAYFb5MFFpNdu_tTlRA',
    appId: '1:548956936579:web:f1b081fa1bbe12d4b47eb6',
    messagingSenderId: '548956936579',
    projectId: 'landmark-navigation-app',
    authDomain: 'landmark-navigation-app.firebaseapp.com',
    storageBucket: 'landmark-navigation-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU2YmQ975V4gV4leae3ia2IKJzWGZFxxU',
    appId: '1:548956936579:android:cb00a0b401a4b5c4b47eb6',
    messagingSenderId: '548956936579',
    projectId: 'landmark-navigation-app',
    storageBucket: 'landmark-navigation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlGCAIYpsawRI4miBQn7GVBolHN5dDoJM',
    appId: '1:548956936579:ios:92d7423616749b5cb47eb6',
    messagingSenderId: '548956936579',
    projectId: 'landmark-navigation-app',
    storageBucket: 'landmark-navigation-app.firebasestorage.app',
    iosBundleId: 'com.example.landmarkNavigationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlGCAIYpsawRI4miBQn7GVBolHN5dDoJM',
    appId: '1:548956936579:ios:92d7423616749b5cb47eb6',
    messagingSenderId: '548956936579',
    projectId: 'landmark-navigation-app',
    storageBucket: 'landmark-navigation-app.firebasestorage.app',
    iosBundleId: 'com.example.landmarkNavigationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbWrFMbZgxfSnbxAYFb5MFFpNdu_tTlRA',
    appId: '1:548956936579:web:a70c789d747a02ffb47eb6',
    messagingSenderId: '548956936579',
    projectId: 'landmark-navigation-app',
    authDomain: 'landmark-navigation-app.firebaseapp.com',
    storageBucket: 'landmark-navigation-app.firebasestorage.app',
  );
}
